export const GET_ACCESS_TOKEN_FETCH = '@@auth/GET_ACCESS_TOKEN_FETCH';
export const GET_ACCESS_TOKEN_SUCCESS = '@@auth/GET_ACCESS_TOKEN_SUCCESS';
export const GET_ACCESS_TOKEN_FAILURE = '@@auth/GET_ACCESS_TOKEN_FAILURE';

export const REFRESH_ACCESS_TOKEN_FETCH = '@@auth/REFRESH_ACCESS_TOKEN_FETCH';
export const REFRESH_ACCESS_TOKEN_SUCCESS = '@@auth/REFRESH_ACCESS_TOKEN_SUCCESS';
export const REFRESH_ACCESS_TOKEN_FAILURE = '@@auth/REFRESH_ACCESS_TOKEN_FAILURE';