export const GET_ACCOUNT_FETCH = '@@pushsms/GET_ACCOUNT_FETCH';
export const GET_ACCOUNT_SUCCESS = '@@pushsms/GET_ACCOUNT_SUCCESS';
export const GET_ACCOUNT_FAILURE = '@@pushsms/GET_ACCOUNT_FAILURE';

export const DELIVERY_MESSAGE_FETCH = '@@pushsms/DELIVERY_MESSAGE_FETCH';
export const DELIVERY_MESSAGE_SUCCESS = '@@pushsms/DELIVERY_MESSAGE_SUCCESS';
export const DELIVERY_MESSAGE_FAILURE = '@@pushsms/DELIVERY_MESSAGE_FAILURE';

export const GET_STATUS_FETCH = '@@pushsms/GET_STATUS_FETCH';
export const GET_STATUS_SUCCESS = '@@pushsms/GET_STATUS_SUCCESS';
export const GET_STATUS_FAILURE = '@@pushsms/GET_STATUS_FAILURE';

export const CALCULATE_BULK_DELIVERY_FETCH = '@@pushsms/CALCULATE_BULK_DELIVERY_FETCH';
export const CALCULATE_BULK_DELIVERY_SUCCESS = '@@pushsms/CALCULATE_BULK_DELIVERY_SUCCESS';
export const CALCULATE_BULK_DELIVERY_FAILURE = '@@pushsms/CALCULATE_BULK_DELIVERY_FAILURE';

export const DELIVERY_BULK_FETCH = '@@pushsms/DELIVERY_BULK_FETCH';
export const DELIVERY_BULK_SUCCESS = '@@pushsms/DELIVERY_BULK_SUCCESS';
export const DELIVERY_BULK_FAILURE = '@@pushsms/DELIVERY_BULK_FAILURE';