export const GET_ACCOUNT_FETCH = '@@pushsms/GET_ACCOUNT_FETCH';
export const GET_ACCOUNT_SUCCESS = '@@pushsms/GET_ACCOUNT_SUCCESS';
export const GET_ACCOUNT_FAILURE = '@@pushsms/GET_ACCOUNT_FAILURE';

export const DELIVERY_MESSAGE_FETCH = '@@pushsms/DELIVERY_MESSAGE_FETCH';
export const DELIVERY_MESSAGE_SUCCESS = '@@pushsms/DELIVERY_MESSAGE_SUCCESS';
export const DELIVERY_MESSAGE_FAILURE = '@@pushsms/DELIVERY_MESSAGE_FAILURE';

export const GET_STATUS_FETCH = '@@pushsms/GET_STATUS_FETCH';
export const GET_STATUS_SUCCESS = '@@pushsms/GET_STATUS_SUCCESS';
export const GET_STATUS_FAILURE = '@@pushsms/GET_STATUS_FAILURE';

export const CALCULATE_BULK_DELIVERY_FETCH = '@@pushsms/CALCULATE_BULK_DELIVERY_FETCH';
export const CALCULATE_BULK_DELIVERY_SUCCESS = '@@pushsms/CALCULATE_BULK_DELIVERY_SUCCESS';
export const CALCULATE_BULK_DELIVERY_FAILURE = '@@pushsms/CALCULATE_BULK_DELIVERY_FAILURE';

export const DELIVERY_BULK_FETCH = '@@pushsms/DELIVERY_BULK_FETCH';
export const DELIVERY_BULK_SUCCESS = '@@pushsms/DELIVERY_BULK_SUCCESS';
export const DELIVERY_BULK_FAILURE = '@@pushsms/DELIVERY_BULK_FAILURE';

export const GET_TEMPLATES_FETCH = '@@pushsms/GET_TEMPLATES_FETCH';
export const GET_TEMPLATES_SUCCESS = '@@pushsms/GET_TEMPLATES_SUCCESS';
export const GET_TEMPLATES_FAILURE = '@@pushsms/GET_TEMPLATES_FAILURE';

export const CREATE_TEMPLATE_FETCH = '@@pushsms/CREATE_TEMPLATE_FETCH';
export const CREATE_TEMPLATE_SUCCESS = '@@pushsms/CREATE_TEMPLATE_SUCCESS';
export const CREATE_TEMPLATE_FAILURE = '@@pushsms/CREATE_TEMPLATE_FAILURE';

export const DELETE_TEMPLATE_FETCH = '@@pushsms/DELETE_TEMPLATE_FETCH';
export const DELETE_TEMPLATE_SUCCESS = '@@pushsms/DELETE_TEMPLATE_SUCCESS';
export const DELETE_TEMPLATE_FAILURE = '@@pushsms/DELETE_TEMPLATE_FAILURE';

export const UPDATE_TEMPLATE_FETCH = '@@pushsms/UPDATE_TEMPLATE_FETCH';
export const UPDATE_TEMPLATE_SUCCESS = '@@pushsms/UPDATE_TEMPLATE_SUCCESS';
export const UPDATE_TEMPLATE_FAILURE = '@@pushsms/UPDATE_TEMPLATE_FAILURE';